import { db } from '../src/lib/db'

async function main() {
  // Create templates for each service
  const services = await db.service.findMany()

  for (const service of services) {
    const templateContent = generateTemplateContent(service.code, service.name)
    
    await db.template.create({
      data: {
        name: `Template ${service.name}`,
        content: templateContent,
        serviceId: service.id
      }
    })
  }

  console.log('Templates created successfully!')
}

function generateTemplateContent(serviceCode: string, serviceName: string): string {
  const currentDate = new Date().toLocaleDateString('id-ID')
  
  const baseTemplate = `
PEMERINTAH DESA [NAMA DESA]
KECAMATAN [NAMA KECAMATAN]
KABUPATEN [NAMA KABUPATEN]

----------------------------------------------------------------------
                           ${serviceName.toUpperCase()}
----------------------------------------------------------------------

Nomor Tracking: {{trackingNumber}}
Tanggal: {{currentDate}}

DATA PEMOHON:
Nama: {{fullName}}
Email: {{email}}
No. Telepon: {{phone}}
Alamat: {{address}}
NIK: {{nik}}
Tempat/Tanggal Lahir: {{birthPlace}} / {{birthDate}}
Jenis Kelamin: {{gender}}
Pekerjaan: {{occupation}}

TUJUAN PEMOHONAN:
{{purpose}}

INFORMASI TAMBAHAN:
{{additionalInfo}}

KETERANGAN:
Dokumen ini diterbitkan berdasarkan permohonan yang diajukan melalui 
Sistem Pelayanan Desa dengan data yang tercantum di atas.

Ditetapkan di: [NAMA DESA]
Pada tanggal: ${currentDate}

Kepala Desa,
[Nama Kepala Desa]
[NIP Kepala Desa]

----------------------------------------------------------------------
Dokumen ini sah dan dapat dipertanggungjawabkan.
Generated by Sistem Pelayanan Desa
----------------------------------------------------------------------
`

  return baseTemplate
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })